# Generated by Django 4.1 on 2022-08-22 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "countryId",
                    models.IntegerField(
                        db_column="country_id",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("country", models.CharField(max_length=80)),
            ],
        ),
    ]
