# Generated by Django 4.1 on 2022-08-24 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("truesight", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PredictionType",
            fields=[
                (
                    "predictionTypeId",
                    models.AutoField(
                        db_column="prediction_type_id",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "predictionType",
                    models.CharField(db_column="prediction_type", max_length=80),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StatExportType",
            fields=[
                (
                    "statExportTypeId",
                    models.AutoField(
                        db_column="stat_export_type_id",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "statExportType",
                    models.CharField(db_column="stat_export_type", max_length=80),
                ),
            ],
        ),
        migrations.CreateModel(
            name="University",
            fields=[
                (
                    "universityId",
                    models.AutoField(
                        db_column="university_id",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("university", models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "userId",
                    models.AutoField(
                        db_column="user_id",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("email", models.CharField(default="", max_length=255, unique=True)),
                ("password", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="UserType",
            fields=[
                (
                    "userTypeId",
                    models.AutoField(
                        db_column="user_type_id",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("userType", models.CharField(db_column="user_type", max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name="country",
            name="countryId",
            field=models.AutoField(
                db_column="country_id", primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                (
                    "userInfoId",
                    models.AutoField(
                        db_column="user_info_id",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("firstName", models.CharField(db_column="first_name", max_length=255)),
                ("lastName", models.CharField(db_column="last_name", max_length=255)),
                (
                    "creationDate",
                    models.TimeField(auto_now_add=True, db_column="creation_date"),
                ),
                (
                    "updatedDate",
                    models.TimeField(auto_now_add=True, db_column="updated_date"),
                ),
                (
                    "countryId",
                    models.ForeignKey(
                        db_column="country_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="truesight.country",
                    ),
                ),
                (
                    "universityId",
                    models.ForeignKey(
                        db_column="university_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="truesight.university",
                    ),
                ),
                (
                    "userId",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="truesight.user",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="userTypeId",
            field=models.ForeignKey(
                db_column="user_type_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="truesight.usertype",
            ),
        ),
        migrations.AddField(
            model_name="university",
            name="countryId",
            field=models.ForeignKey(
                db_column="country_id",
                default=138,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="truesight.country",
            ),
        ),
        migrations.CreateModel(
            name="StatExport",
            fields=[
                (
                    "statExportId",
                    models.AutoField(
                        db_column="stat_export_id",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "exportDate",
                    models.TimeField(auto_now_add=True, db_column="export_date"),
                ),
                (
                    "statExportTypeId",
                    models.ForeignKey(
                        db_column="stat_export_type_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="truesight.statexporttype",
                    ),
                ),
                (
                    "userId",
                    models.ForeignKey(
                        db_column="user_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="truesight.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PredictionTraining",
            fields=[
                (
                    "predictionTrainingId",
                    models.AutoField(
                        db_column="prediction_training_id",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("gmatScore", models.IntegerField(db_column="gmat_score", default=0)),
                (
                    "gpaScore",
                    models.DecimalField(
                        db_column="gpa_score", decimal_places=2, default=0, max_digits=3
                    ),
                ),
                ("work_exp", models.IntegerField(db_column="work_exp", default=0)),
                (
                    "gradGpaScore",
                    models.DecimalField(
                        db_column="grad_gpa_score",
                        decimal_places=2,
                        default=0,
                        max_digits=3,
                    ),
                ),
                (
                    "OaAtGrad",
                    models.BooleanField(db_column="OA_at_grad", default=False),
                ),
                ("OaAt90", models.BooleanField(db_column="OA_at_90", default=False)),
                ("GradYear", models.IntegerField(db_column="grad_year")),
                ("Salary", models.IntegerField(db_column="salary", default=0)),
                (
                    "predictionTypeId",
                    models.ForeignKey(
                        blank=True,
                        db_column="prediction_type_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="truesight.predictiontype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Prediction",
            fields=[
                (
                    "predictionId",
                    models.AutoField(
                        db_column="prediction_id",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("gmatScore", models.IntegerField(db_column="gmat_score", default=0)),
                (
                    "gpaScore",
                    models.DecimalField(
                        db_column="gpa_score", decimal_places=2, default=0, max_digits=3
                    ),
                ),
                ("work_exp", models.IntegerField(db_column="work_exp", default=0)),
                (
                    "gradGpaScore",
                    models.DecimalField(
                        db_column="grad_gpa_score",
                        decimal_places=2,
                        default=0,
                        max_digits=3,
                    ),
                ),
                (
                    "creationDate",
                    models.TimeField(auto_now_add=True, db_column="creation_date"),
                ),
                (
                    "massivePredictionId",
                    models.IntegerField(
                        blank=True,
                        db_column="massive_prediction_id",
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "predictionTypeId",
                    models.ForeignKey(
                        blank=True,
                        db_column="prediction_type_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="truesight.predictiontype",
                    ),
                ),
                (
                    "userId",
                    models.ForeignKey(
                        db_column="user_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="truesight.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LoginAttempt",
            fields=[
                (
                    "loginId",
                    models.AutoField(
                        db_column="login_id",
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "loginAttemptDate",
                    models.TimeField(auto_now_add=True, db_column="login_attempt_date"),
                ),
                (
                    "isSuccesfull",
                    models.BooleanField(db_column="is_successful", default=False),
                ),
                (
                    "userId",
                    models.ForeignKey(
                        db_column="user_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="truesight.user",
                    ),
                ),
            ],
        ),
    ]
