# Generated by Django 4.1 on 2022-08-25 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("truesight", "0002_predictiontype_statexporttype_university_user_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(name="country", table="country",),
        migrations.AlterModelTable(name="loginattempt", table="login_attempt",),
        migrations.AlterModelTable(name="prediction", table="prediction",),
        migrations.AlterModelTable(
            name="predictiontraining", table="prediction_training",
        ),
        migrations.AlterModelTable(name="predictiontype", table="prediction_type",),
        migrations.AlterModelTable(name="statexport", table="stat_export",),
        migrations.AlterModelTable(name="statexporttype", table="stat_export_type",),
        migrations.AlterModelTable(name="university", table="university",),
        migrations.AlterModelTable(name="user", table="user",),
        migrations.AlterModelTable(name="userinfo", table="user_info",),
        migrations.AlterModelTable(name="usertype", table="user_type",),
    ]
